### ISSUE TITLE
could not install

### ISSUE THREAD

**Issue by cailiangliang765** [zwdzwd/sesameData#1]
Installing package into '/home/rstudio/R/x86_64-pc-linux-gnu-library/3.6'
(as 'lib' is unspecified)
* installing *source* package 'sesameData' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Warning: download failed
  hub path: 'https://experimenthub.bioconductor.org/fetch/1668'
  cache resource: 'EH1668 : 1668'
  reason: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
Error: package or namespace load failed for 'sesameData':
 .onAttach failed in attachNamespace() for 'sesameData', details:
  call: NULL
  error: 1 resources failed to download
Error: loading failed
Execution halted
ERROR: loading failed
* removing '/home/rstudio/R/x86_64-pc-linux-gnu-library/3.6/sesameData'
* restoring previous '/home/rstudio/R/x86_64-pc-linux-gnu-library/3.6/sesameData'

**Comment by zwdzwd** [comment]
Hi this seems an ExperimentHub inaccessibility issue. Did you install from BioC or directly from github?

**Comment by cailiangliang765** [comment]
> Hi this seems an ExperimentHub inaccessibility issue. Did you install from BioC or directly from github?

Hi @zwdzwd Thanks for your quick reply! I can install it by BioC today. Perhaps it was internet unreached  yesterday.  Thank you.
