### ISSUE TITLE
can't install sesameData

### ISSUE THREAD

**Issue by zhaoliang0302** [zwdzwd/sesameData#2]
```
* installing *source* package 'sesameData' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'sesameData'
    finding HTML links ... done
    sesameDataCacheAll                      html  
    sesameDataGet                           html  
    sesameDataList                          html  
    sesameDataListDates                     html  
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
Warning: download failed
  web resource path: 'https://experimenthub.bioconductor.org/fetch/1680'
  local file path: 'C:\Users\ZHAOLI~1\AppData\Local\Temp\RtmpKyHDJP/BiocFileCache/20a07774319_1680'
  reason: transfer closed with 3545467 bytes remaining to read
Warning: bfcadd() failed; resource removed
  rid: BFC19
  fpath: 'https://experimenthub.bioconductor.org/fetch/1680'
  reason: download failed
Warning: download failed
  hub path: 'https://experimenthub.bioconductor.org/fetch/1680'
  cache resource: 'EH1680 : 1680'
  reason: bfcadd() failed; see warnings()
Error: package or namespace load failed for 'sesameData':
 .onAttach failed in attachNamespace() for 'sesameData', details:
  call: NULL
  error: 1 resources failed to download
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Program Files/R/R-3.6.0/library/sesameData'
```

**Comment by zhaoliang0302** [comment]
it seems bad network but I can't download via R due to the unstable network. Is there any advice to download the files this package needed? 
Thanks

**Comment by zhaoliang0302** [comment]
````
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 tools_3.6.0   
```

**Comment by ghost** [comment]
Hi, I have your exactly same issue. Did you found a way to solve it?

**Comment by zhaoliang0302** [comment]
> Hi, I have your exactly same issue. Did you found a way to solve it?

I didn't solve this problem and give up using this package. I 'm sorry I can't help you.

**Comment by zwdzwd** [comment]
Sorry for the frustration and the delay in response. I have implemented backup download sources (starting 1.8 and 1.9) and hopefully that makes the package work even when ExperimentHub is not functioning well. Let me know.

**Comment by zyazdani12** [comment]
Hi, I'm getting the following error when I try to install sesameData even though I have re-installed ExperimentHub and sesame a few times with force = TRUE. Am I missing something obvious? 

> BiocManager::install("sesameData")
Warning message:
In install.packages(...) :
  installation of package ‘sesameData’ had non-zero exit status

Thank you in advance for reading!

**Comment by zwdzwd** [comment]
@zyazdani12 Could it be your R version is too old? Just guessing. Can you provide more info on your system?

**Comment by zyazdani12** [comment]
@zwdzwd Yes, absolutely. I'm using a windows 10 enterprise with the following R version 4.3 (R.Version() pasted below). Should I try uninstalling re-installing R? 

$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$crt
[1] "ucrt"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "4"

$minor
[1] "3.0"

$year
[1] "2023"

$month
[1] "04"

$day
[1] "21"

$`svn rev`
[1] "84292"

$language
[1] "R"

$version.string
[1] "R version 4.3.0 (2023-04-21 ucrt)"

$nickname
[1] "Already Tomorrow"

Computer information
![image](https://github.com/zwdzwd/sesameData/assets/134552209/004957bf-b0b0-47ed-9292-412e096de14e)

**Comment by zwdzwd** [comment]
Hmm, looks like your R is very new. Sorry, I haven't had any experience with windows. It's interesting that the Bioconductor windows binary is not available yet. https://bioconductor.org/packages/release/data/experiment/html/sesameData.html
Not sure if this has to do with the fact BioC just updated about a month ago. Can you install ExperimentHub without issue?

**Comment by zyazdani12** [comment]
Yes, no issues with ExperimentHub, although I can't complete library(sesame) because the sesameData dependency isn't working. 

I see does that mean I have to wait until the windows binary is available? 

And it's no worries! I use your really wonderful tools on my mac and other windows computer all the time, have just been having trouble setting everything up on this new machine.

**Comment by zwdzwd** [comment]
That's my guess. Have you tried `BiocManager::install("zwdzwd/sesameData")`?

**Comment by zyazdani12** [comment]
Hi, thank you! Thankfully that line actually gave a different error which required me to install Bioconductor remotes. I'm also unable to install that and I'm looking into that one now.
