### ISSUE TITLE
HM450.hg38.manifest one duplicated position ?

### ISSUE THREAD

**Issue by tiagochst** [zwdzwd/sesameData#5]
@zwdzwd It seems there are two probes in the same ranges. Is this correct? 
`packageVersion("sesameData") [1] ‘1.6.0’`

Code:
```
hm450 <- sesameDataGet("HM450.hg38.manifest")
hm450[c("cg26712673","cg04746089")]
```
<img width="914" alt="Screen Shot 2020-09-10 at 4 22 01 PM" src="https://user-images.githubusercontent.com/145529/92799567-e534e080-f381-11ea-98c0-0e4564f2f350.png">

**Comment by zwdzwd** [comment]
That's right. It's a known issue after mapping to hg38.
