### ISSUE TITLE
Warning message: In message(cond, appendLF = TRUE) : additional arguments ignored in message()

### ISSUE THREAD

**Issue by HenrikBengtsson** [zwdzwd/sesameData#6]
FYI, while check reverse dependencies for **matrixStats**, I spotted warning on:

```r
Warning message:
In message(cond, appendLF = TRUE) :
  additional arguments ignored in message()
```

which I suspect comes from this pages, e.g. https://github.com/zwdzwd/sesameData/blob/f94ae91b3e3be6e3bd03ad4fb41bc6498db750e7/R/data.R#L11-L25.  

Here's what's going on:

```r
> cond <- simpleMessage("foo")
> message(cond)
foo
> message(cond, appendLF = TRUE)
fooWarning message:
In message(cond, appendLF = TRUE) :
  additional arguments ignored in message()
```

**Comment by zwdzwd** [comment]
Sorry I just saw this. I think you are right. the appendLF is now removed. Thanks for reporting
